[package]
default-run = "poem-admin"
edition = "2021"
name = "poem-admin"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

app = {path = "../app"}
configs = {path = "../configs"}
db = {path = "../db"}
#
# poem = {version = "1.3", features = ["static-files", "rustls", "compression", "multipart", "tokio-metrics"]}
poem = {version = "1.3", features = ["static-files", "rustls", "compression", "multipart"]}
poem-openapi = { version = "2.0", features = ["swagger-ui", "chrono"]}
#
tracing = "0.1"
tracing-appender = "0.2"
# tracing-log = "0.1"
tokio = {version = "1", features = ["rt-multi-thread", "macros", "time"]}
tracing-subscriber = {version = "0.3", features = ["json", "env-filter", "local-time", "registry"]}
