//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

use app_derive::QueryObject;
use poem_openapi::Object;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity, Deserialize, Object, QueryObject)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "sys_dict_data"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub dict_data_id: String,
    pub dict_sort: i32,
    pub dict_label: String,
    pub dict_value: String,
    pub dict_type: String,
    pub css_class: Option<String>,
    pub list_class: Option<String>,
    pub is_default: String,
    pub status: String,
    pub create_by: String,
    pub update_by: Option<String>,
    pub remark: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Object, QueryObject)]
pub struct SysDictDataModel {
    pub dict_data_id: String,
    pub dict_sort: i32,
    pub dict_label: String,
    pub dict_value: String,
    pub dict_type: String,
    pub css_class: Option<String>,
    pub list_class: Option<String>,
    pub is_default: String,
    pub status: String,
    pub create_by: String,
    pub update_by: Option<String>,
    pub remark: Option<String>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

impl SysDictDataModel {

  pub fn fromVec(it: Vec<Model>) -> Vec<SysDictDataModel> {
    it.into_iter().map(|ii| ii.into()).collect::<Vec<SysDictDataModel>>()
  }

}

impl From<SysDictDataModel> for Model {
  fn from(it: SysDictDataModel) -> Self {
    Self {
      dict_data_id: it.dict_data_id,
      dict_sort: it.dict_sort,
      dict_label: it.dict_label,
      dict_value: it.dict_value,
      dict_type: it.dict_type,
      css_class: it.css_class,
      list_class: it.list_class,
      is_default: it.is_default,
      status: it.status,
      create_by: it.create_by,
      update_by: it.update_by,
      remark: it.remark,
      created_at: it.created_at,
      updated_at: it.updated_at,
      deleted_at: it.deleted_at
    }
  }
}

impl From<Model> for SysDictDataModel {
  fn from(it: Model) -> Self {
    Self {
      dict_data_id: it.dict_data_id,
      dict_sort: it.dict_sort,
      dict_label: it.dict_label,
      dict_value: it.dict_value,
      dict_type: it.dict_type,
      css_class: it.css_class,
      list_class: it.list_class,
      is_default: it.is_default,
      status: it.status,
      create_by: it.create_by,
      update_by: it.update_by,
      remark: it.remark,
      created_at: it.created_at,
      updated_at: it.updated_at,
      deleted_at: it.deleted_at
    }
  }
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    DictDataId,
    DictSort,
    DictLabel,
    DictValue,
    DictType,
    CssClass,
    ListClass,
    IsDefault,
    Status,
    CreateBy,
    UpdateBy,
    Remark,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    DictDataId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::DictDataId => ColumnType::String(Some(32u32)).def(),
            Self::DictSort => ColumnType::Integer.def(),
            Self::DictLabel => ColumnType::String(Some(100u32)).def(),
            Self::DictValue => ColumnType::String(Some(100u32)).def(),
            Self::DictType => ColumnType::String(Some(100u32)).def(),
            Self::CssClass => ColumnType::String(Some(100u32)).def().null(),
            Self::ListClass => ColumnType::String(Some(100u32)).def().null(),
            Self::IsDefault => ColumnType::Char(Some(1u32)).def(),
            Self::Status => ColumnType::Char(Some(1u32)).def(),
            Self::CreateBy => ColumnType::String(Some(32u32)).def(),
            Self::UpdateBy => ColumnType::String(Some(32u32)).def().null(),
            Self::Remark => ColumnType::String(Some(500u32)).def().null(),
            Self::CreatedAt => ColumnType::DateTime.def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def().null(),
            Self::DeletedAt => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
